_wandb:
    value:
        cli_version: 0.26.0
        e:
            rbmptdg0cliq2dmjp0qj2ffr9gpsgpnv:
                args:
                    - --config
                    - configs/vanilla_small.yaml
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "982240026624"
                        used: "95460667392"
                email: sharmautkarsh0504@gmail.com
                executable: /home/utkarsh/miniconda/envs/dl_scratch/bin/python
                git:
                    commit: 6b0000f90051ee474f1c6f2ef5107a5d3d70134c
                    remote: https://github.com/SharmaLlama/dl-from-scratch-LM.git
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-710668a5-1742-2159-596e-f46291b729d6
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-20aeb6fa-9302-ecd4-643f-59d47527e8e2
                host: utkarsh-System-Product-Name
                memory:
                    total: "32760586240"
                os: Linux-6.17.0-22-generic-x86_64-with-glibc2.39
                program: /home/utkarsh/Documents/Projects/dl-from-scratch-LM/scripts/train.py
                python: CPython 3.12.13
                root: /home/utkarsh/Documents/Projects/dl-from-scratch-LM
                startedAt: "2026-04-22T06:28:22.752424Z"
                writerId: rbmptdg0cliq2dmjp0qj2ffr9gpsgpnv
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 49
                - 51
            "2":
                - 1
                - 49
                - 51
            "3":
                - 1
                - 13
                - 15
                - 16
                - 61
            "4": 3.12.13
            "5": 0.26.0
            "12": 0.26.0
            "13": linux-x86_64
data:
    value:
        dataset_path: data/
        num_workers: 4
        tokenizer_path: tokenizer/
        train_ratio: 0.9
model:
    value:
        attention_type: vanilla
        d_ff: 1024
        d_model: 256
        dk: 64
        dropout: 0.1
        dv: 64
        ffn_type: relu
        max_seq_len: 256
        n_heads: 4
        n_layers: 4
        pe_type: sinusoidal
        pre_norm: true
        vocab_size: 50257
training:
    value:
        batch_size: 16
        checkpoint_interval: 50000000
        eval_interval: 10000000
        grad_clip: 1
        label_smoothing: 0
        lr: 0.0003
        max_tokens: 100000000
        seed: 42
        warmup_steps: 200
        weight_decay: 0.1
wandb:
    value:
        entity: null
        log_attention_every: 500
        log_every_steps: 10
        project: dl-from-scratch-lm
        run_name: vanilla-small
        tags:
            - vanilla
            - sinusoidal
            - small
            - debug
        watch_model: true
